import { MyFrame } from "./animatedImage.js"

const frameSize = 16

const frames = {
  right1demonized: new MyFrame({
    name: "right1demonized",
    x: frameSize,
    y: 0,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  right2demonized: new MyFrame({
    name: "right2demonized",
    x: frameSize,
    y: frameSize,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  right3demonized: new MyFrame({
    name: "right3demonized",
    x: frameSize,
    y: frameSize * 2,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  left1demonized: new MyFrame({
    name: "left1demonized",
    x: frameSize,
    y: 0,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  left2demonized: new MyFrame({
    name: "left2demonized",
    x: frameSize,
    y: frameSize,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  left3demonized: new MyFrame({
    name: "left3demonized",
    x: frameSize,
    y: frameSize * 2,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  down1demonized: new MyFrame({
    name: "down1demonized",
    x: frameSize,
    y: frameSize * 3,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  down2demonized: new MyFrame({
    name: "down2demonized",
    x: frameSize,
    y: frameSize * 4,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  down3demonized: new MyFrame({
    name: "down3demonized",
    x: frameSize,
    y: frameSize * 5,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up1demonized: new MyFrame({
    name: "up1demonized",
    x: frameSize,
    y: frameSize * 6,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up2demonized: new MyFrame({
    name: "up2demonized",
    x: frameSize,
    y: frameSize * 7,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up3demonized: new MyFrame({
    name: "up3demonized",
    x: frameSize,
    y: frameSize * 8,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  right1: new MyFrame({
    name: "right1",
    x: frameSize * 2,
    y: 0,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  right2: new MyFrame({
    name: "right2",
    x: frameSize * 2,
    y: frameSize,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  right3: new MyFrame({
    name: "right3",
    x: frameSize * 2,
    y: frameSize * 2,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  left1: new MyFrame({
    name: "left1",
    x: frameSize * 2,
    y: 0,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  left2: new MyFrame({
    name: "left2",
    x: frameSize * 2,
    y: frameSize,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  left3: new MyFrame({
    name: "left3",
    x: frameSize * 2,
    y: frameSize * 2,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  down1: new MyFrame({
    name: "down1",
    x: frameSize * 2,
    y: frameSize * 3,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  down2: new MyFrame({
    name: "down2",
    x: frameSize * 2,
    y: frameSize * 4,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  down3: new MyFrame({
    name: "down3",
    x: frameSize * 2,
    y: frameSize * 5,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up1: new MyFrame({
    name: "up1",
    x: frameSize * 2,
    y: frameSize * 6,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up2: new MyFrame({
    name: "up2",
    x: frameSize * 2,
    y: frameSize * 7,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up3: new MyFrame({
    name: "up3",
    x: frameSize * 2,
    y: frameSize * 8,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
}

export const sheepAnimations = new Map<string, MyFrame[]>([
  ["standRightDemonized", [frames.right1demonized]],
  ["standLeftDemonized", [frames.left1demonized]],
  ["standDownDemonized", [frames.down1demonized]],
  ["standUpDemonized", [frames.up1demonized]],
  [
    "goRightDemonized",
    [
      frames.right1demonized,
      frames.right2demonized,
      frames.right1demonized,
      frames.right3demonized,
    ],
  ],
  [
    "goLeftDemonized",
    [
      frames.left1demonized,
      frames.left2demonized,
      frames.left1demonized,
      frames.left3demonized,
    ],
  ],
  [
    "goDownDemonized",
    [
      frames.down1demonized,
      frames.down2demonized,
      frames.down1demonized,
      frames.down3demonized,
    ],
  ],
  [
    "goUpDemonized",
    [
      frames.up1demonized,
      frames.up2demonized,
      frames.up1demonized,
      frames.up3demonized,
    ],
  ],
  ["standRight", [frames.right1]],
  ["standLeft", [frames.left1]],
  ["standDown", [frames.down1]],
  ["standUp", [frames.up1]],
  ["goRight", [frames.right1, frames.right2, frames.right1, frames.right3]],
  ["goLeft", [frames.left1, frames.left2, frames.left1, frames.left3]],
  ["goDown", [frames.down1, frames.down2, frames.down1, frames.down3]],
  ["goUp", [frames.up1, frames.up2, frames.up1, frames.up3]],
])
