import { MyFrame } from "./animatedImage.js"

const frameSize = 16

const frames = {
  right1: new MyFrame({
    name: "right1",
    x: 0,
    y: 0,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  right2: new MyFrame({
    name: "right2",
    x: 0,
    y: frameSize,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  right3: new MyFrame({
    name: "right3",
    x: 0,
    y: frameSize * 2,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  left1: new MyFrame({
    name: "left1",
    x: 0,
    y: 0,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  left2: new MyFrame({
    name: "left2",
    x: 0,
    y: frameSize,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  left3: new MyFrame({
    name: "left3",
    x: 0,
    y: frameSize * 2,
    width: frameSize,
    height: frameSize,
    flipAlongX: true,
    flipAlongY: false,
  }),
  down1: new MyFrame({
    name: "down1",
    x: 0,
    y: frameSize * 3,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  down2: new MyFrame({
    name: "down2",
    x: 0,
    y: frameSize * 4,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  down3: new MyFrame({
    name: "down3",
    x: 0,
    y: frameSize * 5,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up1: new MyFrame({
    name: "up1",
    x: 0,
    y: frameSize * 6,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up2: new MyFrame({
    name: "up2",
    x: 0,
    y: frameSize * 7,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
  up3: new MyFrame({
    name: "up3",
    x: 0,
    y: frameSize * 8,
    width: frameSize,
    height: frameSize,
    flipAlongX: false,
    flipAlongY: false,
  }),
}

export const heroAnimations = new Map<string, MyFrame[]>([
  ["standRight", [frames.right1]],
  ["standLeft", [frames.left1]],
  ["standDown", [frames.down1]],
  ["standUp", [frames.up1]],
  ["goRight", [frames.right1, frames.right2, frames.right1, frames.right3]],
  ["goLeft", [frames.left1, frames.left2, frames.left1, frames.left3]],
  ["goDown", [frames.down1, frames.down2, frames.down1, frames.down3]],
  ["goUp", [frames.up1, frames.up2, frames.up1, frames.up3]],
])
